### ISSUE TITLE
Thanks for sharing the code!

### ISSUE THREAD

**Issue by AwayFromKeyboardwarrior** [richard-peng-xia/MMed-RAG#1]
I have one more question. are you going to share your training code, or model weight?

Thank you!

**Comment by richard-peng-xia** [comment]
Hi, @AwayFromKeyboardwarrior .

Thanks for your attention. We will release the code and data asap. Stay tuned!

**Comment by AwayFromKeyboardwarrior** [comment]
Thank you so much! I have been struggling with training the model for the last few months. do you have any sample code you can upload, or reference code from other git?
Thank you!

**Comment by richard-peng-xia** [comment]
Hi, we have updated the repo. Thanks.
