### ISSUE TITLE
Inquiry About Inference and Scoring Code

### ISSUE THREAD

**Issue by Jack-ZC8** [richard-peng-xia/MMed-RAG#10]
First, I want to express my appreciation for the amazing work you’ve done in creating and maintaining this open-source project. 

I have a question regarding the inference and scoring code. Could you please provide some guidance or direct me to where I might find the relevant code?

Thank you for your time and assistance!

**Comment by richard-peng-xia** [comment]
Hi @Jack-ZC8 ,

Sorry to bother you.

For the inference part, please refer to [this repo](https://github.com/richard-peng-xia/RULE) for more details.

Thanks.

**Comment by adhiiisetiawan** [comment]
Hi @richard-peng-xia how about the scoring code for outputing the metrics like Acc, F1, Auc, BLEU, etc? Where should i refer?

**Comment by richard-peng-xia** [comment]
Hi @adhiiisetiawan ,

About metrics like bleu, you can refer to [this](https://github.com/richard-peng-xia/RULE/issues/8).

For metrics like acc, it is a classification metrics, which is easy to implement.
