### ISSUE TITLE
Question about image choice in IU-Xray

### ISSUE THREAD

**Issue by zzzqzhou** [richard-peng-xia/MMed-RAG#2]
Hi authors,

Thanks for your great work. I have a question about the image choice when test on IU-Xray report generation task. In your shared test data, each sample in IU-Xray report generation task has two images. Which image did you choose for test?

**Comment by richard-peng-xia** [comment]
Hi @zzzqzhou,

Following most work related to report generation task, choosing a x-ray taken from the front is fine.

Thanks for your attention.
