### ISSUE TITLE
Something about paper

### ISSUE THREAD

**Issue by lzhptr** [richard-peng-xia/MMed-RAG#3]
![image](https://github.com/user-attachments/assets/87f9f896-a9d8-4607-aa42-7abd4ac774cf)

Hello, are Yw,o1, Yl,o1 here the same?

**Comment by richard-peng-xia** [comment]
Hi @lzhptr,

$y_{w,o}$: preferred responses, $y_{l,o}$: dispreferred responses.

Please free to ask if you have any questions.

**Comment by lzhptr** [comment]
> Hi @lzhptr,
> 
> y w , o : preferred responses, y l , o : dispreferred responses.
> 
> Please free to ask if you have any questions.


Thank you, but what I mean is that in this formula,   Yw,o and Yl,o have the same values ​​as y(line 7,8)?

**Comment by richard-peng-xia** [comment]
Yes, you are right. You can check the objective of cross-modality misalignment. 
Thanks for your question.

**Comment by lzhptr** [comment]
> 是的，你说得对。你可以检查跨模态错位的目标。 谢谢你的提问。

Thank you very much! But I still have a question. The good cases and bad cases of DPO here are the same. Why do we need to train like this? Shouldn't DPO widen the gap between good cases and bad cases? Thank you very much again!

**Comment by richard-peng-xia** [comment]
The input images of preference pairs are different in cross-modality alignment stage. You can refer to section 3 (1) in Figure 1. Sorry for bothering you. I will make it more understandable in the next version.

**Comment by lzhptr** [comment]
> The input images of preference pairs are different in cross-modality alignment stage. You can refer to section 3 (1) in Figure 1. Sorry for bothering you. I will make it more understandable in the next version.

Thanks u
