### ISSUE TITLE
about the dpo data

### ISSUE THREAD

**Issue by Key-lei** [richard-peng-xia/MMed-RAG#4]
Great work! Regarding the DPO dataset, are the choose and reject of the VQA type yes or no? If so, has the author encountered the problem that the DPO model deviates from the SFT model? Because I have built a similar DPO dataset myself, I found that as the amount of DPO data increases, such similar yes or no data may seriously cause problems in the generalization of the DPO model

**Comment by richard-peng-xia** [comment]
Hi @Key-lei,

Great question! This is a typical problem caused by DPO. So to overcome this imbalance, our data scale is not very large. Actually maybe you can think deeply about this issue.

Feel free to contact me if you have any question.
