### ISSUE TITLE
 Release the training code

### ISSUE THREAD

**Issue by MiladMolazadeh** [richard-peng-xia/MMed-RAG#5]
Thank you for the great research and all the work you’ve shared! 
Could you share an estimated release timeline for the training code scripts? 

[Reference: Schedule](https://github.com/richard-peng-xia/MMed-RAG?tab=readme-ov-file#-schedule)

**Comment by richard-peng-xia** [comment]
Hi @MiladMolazadeh,

Thanks for your attention.

We will release our code asap. We are rushing for a submission right now.
Sorry to bother you.

**Comment by richard-peng-xia** [comment]
Hi, we have updated the repo. Thanks.
