### ISSUE TITLE
Maybe lost some file like utils and training?

### ISSUE THREAD

**Issue by KeoYang** [richard-peng-xia/MMed-RAG#6]
Dear author. 

 I want to ask where is the **utils.py**、 **training.py**  and any else file in your project.

1. llava-med-1.5_closed-vqa_parellel.py
`from utils import QuestionDataset, setup, cleanup, tensor_to_serializable
`
https://github.com/richard-peng-xia/MMed-RAG/blob/a61de2f9d7220dc8b769c7447262c6405db078af/inference/llava-med-1.5_closed-vqa_parellel.py#L39

2. retrieve_clip_VQA.py
`from training.data import HarvardDataset,HarvardVQADataset
`
https://github.com/richard-peng-xia/MMed-RAG/blob/a61de2f9d7220dc8b769c7447262c6405db078af/retrieve/retrieve_clip_VQA.py#L13

Can you release these files, thanks?

**Comment by richard-peng-xia** [comment]
Hi @KeoYang,

we will upload all this code asap. Stay in tuned!

**Comment by richard-peng-xia** [comment]
Hi, we have updated the repo. You can check this.
Thanks.
