### ISSUE TITLE
Questions about the  structure of the retriever

### ISSUE THREAD

**Issue by Da1daidaidai** [richard-peng-xia/MMed-RAG#7]
very nice work! 
having some questions when reading the retrieve part code.
In the paper, 

> For thetraining of retriever, the vision encoder is a ResNet-50 (He et al., 2016), and the text encoder is a bio-BioClinicalBERT (Alsentzer et al., 2019).  

while I am going through the script

> --model hf-hub:thaottn/OpenCLIP-resnet50-CC12M \

The text encoder for this pre-training weight does not appear to be bio-BioClinicalBERT (Alsentzer et al., 2019)，isn't it?
This may be a stupid question due to some code I overlooked, but I'd still like your answer, thanks!

**Comment by richard-peng-xia** [comment]
Hi @Da1daidaidai,

In this experiment, when using OpenCLIP checkpoints, the model performance is more stable. But you can also use BioMedCLIP as we said in the paper, and the difference is not much.
