### ISSUE TITLE
deepspeed issue

### ISSUE THREAD

**Issue by ghzamani** [richard-peng-xia/MMed-RAG#8]
Hi,  

Thank you for updating your repository. Could you please share the `zero3.json` configuration file used with DeepSpeed? It might help resolve the issue I’m facing.  

I was running /train/dpo/train_dpo_2stages.py with `bf16` and `tf32` set to `false` since my GPU does not support them. I used the default DeepSpeed configuration, but I encountered the following error:  

```  
File "/miniconda3/envs/MMed-RAG/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 529, in defragment  
    assert len(set(t.dtype for t in tensors)) == 1  
AssertionError  
```

**Comment by Kelvinz-89757** [comment]
Hi! We updated the relevant config files. Please check whether that could help.
