### ISSUE TITLE
harvard_val_1000.json can't  read by  line?

### ISSUE THREAD

**Issue by xinyunxing** [richard-peng-xia/MMed-RAG#9]
![image](https://github.com/user-attachments/assets/f3545b51-eba3-4d3f-aaf9-78c284ef4f31)
![image](https://github.com/user-attachments/assets/e2af28d2-2924-4434-8e3f-c65ac412a7db)
When  I  run   /data/quan/MMed-RAG/scripts/retrieve_clip_VQA.sh,it  has  bug " Expecting value: line 2 column 1 (char 2)",but harvard_val_1000.json can't  read by  line ?

**Comment by xinyunxing** [comment]
Is  my  set  wrong?

**Comment by richard-peng-xia** [comment]
Hi @xinyunxing ,

Maybe you can validate the JSON format, e.g., use an online JSON validator or a Python script to check the file for syntax errors. Or look for non-JSON content, i.e., if the JSON contains metadata, logs, or other non-JSON content, you will need to clean it. The file should only include valid JSON objects.

**Comment by xinyunxing** [comment]
![image](https://github.com/user-attachments/assets/ad6602e5-9838-45a8-9f8e-8f30b1e3e3eb)
 请问您这里是已经通过检索器处理后的偏好数据么，然后我就用这个数据直接微调模型行么，感觉出来的结果不好，是需要再怎么处理么，根据您的哪个文件进行处理呢？

**Comment by richard-peng-xia** [comment]
你需要根据你微调后检索器的表现来针对性地选择偏好数据，比如在经过你训练好的检索器上出现了过度依赖的问题，选择这部分数据来构建偏好数据，从而针对性解决这个问题。

**Comment by xinyunxing** [comment]
请问有构建偏好数据集的参考代码么？
